# Generated by Django 3.0.4 on 2020-03-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='pop_2010',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='county',
            name='fips',
            field=models.CharField(max_length=5),
        ),
    ]
