# Generated by Django 3.0.4 on 2020-03-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20200323_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countytestdate',
            name='scrape_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
