# Generated by Django 3.0.4 on 2020-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200323_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countytestdate',
            old_name='case_count',
            new_name='cumulative_count',
        ),
        migrations.AddField(
            model_name='countytestdate',
            name='daily_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
