# Generated by Django 3.0.4 on 2020-03-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_currenttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='countytestdate',
            name='cumulative_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countytestdate',
            name='daily_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
