# Generated by Django 3.0.4 on 2020-04-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20200327_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatewideTotalDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_positive_tests', models.IntegerField(default=0)),
                ('cumulative_completed_tests', models.IntegerField(default=0)),
                ('cumulative_completed_mdh', models.IntegerField(default=0)),
                ('cumulative_completed_private', models.IntegerField(default=0)),
                ('cumulative_hospitalized', models.IntegerField(default=0)),
                ('currently_hospitalized', models.IntegerField(default=0)),
                ('currently_in_icu', models.IntegerField(default=0)),
                ('cumulative_statewide_deaths', models.IntegerField(default=0)),
                ('cumulative_statewide_recoveries', models.IntegerField(default=0)),
                ('scrape_date', models.DateField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentTotal',
        ),
    ]
