# Generated by Django 3.0.5 on 2020-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20200410_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cases_age_0_5',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cases_age_20_44',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cases_age_45_64',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cases_age_65_plus',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cases_age_6_19',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cases_age_unknown',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
