# Generated by Django 3.0.5 on 2020-05-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20200412_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatewideAgeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_date', models.DateField()),
                ('age_group', models.CharField(max_length=100)),
                ('cases_pct', models.IntegerField(default=None, null=True)),
                ('deaths_pct', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='statewidetotaldate',
            name='cases_age_0_5',
        ),
        migrations.RemoveField(
            model_name='statewidetotaldate',
            name='cases_age_20_44',
        ),
        migrations.RemoveField(
            model_name='statewidetotaldate',
            name='cases_age_45_64',
        ),
        migrations.RemoveField(
            model_name='statewidetotaldate',
            name='cases_age_65_plus',
        ),
        migrations.RemoveField(
            model_name='statewidetotaldate',
            name='cases_age_6_19',
        ),
        migrations.RemoveField(
            model_name='statewidetotaldate',
            name='cases_age_unknown',
        ),
    ]
