# Generated by Django 3.0.6 on 2020-05-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_statewideagedate_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_date', models.DateField()),
                ('age_group', models.CharField(max_length=100)),
                ('actual_age', models.IntegerField(null=True)),
                ('bool_ltc', models.NullBooleanField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.County')),
            ],
        ),
    ]
