# Generated by Django 3.0.6 on 2020-05-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_death'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroupPop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
