# Generated by Django 3.0.6 on 2020-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_statewidecasesbysampledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='sample_date',
            field=models.DateField(null=True),
        ),
    ]
