# Generated by Django 3.0.6 on 2020-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20200514_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatewideTestsDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField(null=True)),
                ('new_state_tests', models.IntegerField(default=0)),
                ('new_external_tests', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('scrape_date', models.DateField()),
            ],
        ),
    ]
