# Generated by Django 3.0.6 on 2020-05-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_statewidetestsdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewidetotaldate',
            name='new_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='new_deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='removed_cases',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
