# Generated by Django 3.0.6 on 2020-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_auto_20200514_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countytestdate',
            old_name='last_update',
            new_name='last_scrape',
        ),
        migrations.AddField(
            model_name='countytestdate',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='statewidecasesbysampledate',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='statewidetestsdate',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
