# Generated by Django 3.0.6 on 2020-06-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20200518_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewidetestsdate',
            name='new_tests',
            field=models.IntegerField(default=0),
        ),
    ]
