# Generated by Django 3.0.6 on 2020-06-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20200518_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statewidetotaldate',
            name='cumulative_positive_tests',
        ),
    ]
