# Generated by Django 3.0.6 on 2020-06-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_remove_statewidetotaldate_cumulative_positive_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewidetotaldate',
            name='cumulative_positive_tests',
            field=models.IntegerField(default=0),
        ),
    ]
