# Generated by Django 3.0.6 on 2020-06-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_statewidetestsdate_new_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewidetestsdate',
            name='new_tests_rolling',
            field=models.FloatField(default=0),
        ),
    ]
