# Generated by Django 3.0.7 on 2020-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_auto_20200624_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewidedeathsdate',
            name='reported_date',
            field=models.DateField(null=True),
        ),
    ]
