# Generated by Django 3.0.7 on 2020-06-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_statewidedeathsdate_reported_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statewidedeathsdate',
            old_name='new_tests_rolling',
            new_name='new_deaths_rolling',
        ),
    ]
