# Generated by Django 3.0.8 on 2020-07-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_statewidetotaldate_hospitalized_total_daily_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCasesDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField()),
                ('zip', models.CharField(max_length=5)),
                ('cumulative_cases', models.IntegerField()),
                ('import_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
