# Generated by Django 3.0.8 on 2020-07-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0031_zipcasesdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcasesdate',
            name='zip',
            field=models.CharField(max_length=7),
        ),
    ]
