# Generated by Django 3.0.8 on 2020-07-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0032_auto_20200721_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcasesdate',
            old_name='cumulative_cases',
            new_name='cases_cumulative',
        ),
    ]
