# Generated by Django 3.0.9 on 2020-08-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_auto_20200721_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegrouppop',
            name='age_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agegrouppop',
            name='age_min',
            field=models.IntegerField(null=True),
        ),
    ]
