# Generated by Django 3.0.9 on 2020-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0036_statewidehospitalizationsdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countytestdate',
            old_name='daily_count',
            new_name='daily_total_cases',
        ),
        migrations.AddField(
            model_name='countytestdate',
            name='cumulative_confirmed_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countytestdate',
            name='cumulative_probable_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetestsdate',
            name='new_antigen_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetestsdate',
            name='new_pcr_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetestsdate',
            name='total_antigen_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetestsdate',
            name='total_pcr_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='confirmed_cases_newly_reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='cumulative_antigen_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='cumulative_confirmed_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='cumulative_confirmed_statewide_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='cumulative_pcr_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='cumulative_probable_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='cumulative_probable_statewide_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidetotaldate',
            name='probable_cases_newly_reported',
            field=models.IntegerField(default=0),
        ),
    ]
