# Generated by Django 3.0.9 on 2020-10-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0037_auto_20201014_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewidecasesbysampledate',
            name='new_antigen_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidecasesbysampledate',
            name='new_pcr_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidecasesbysampledate',
            name='total_antigen_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statewidecasesbysampledate',
            name='total_pcr_tests',
            field=models.IntegerField(default=0),
        ),
    ]
