# Generated by Django 3.0.9 on 2020-10-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0038_auto_20201014_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countytestdate',
            name='cumulative_confirmed_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='countytestdate',
            name='cumulative_deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='countytestdate',
            name='cumulative_probable_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='countytestdate',
            name='daily_deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='new_antigen_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='new_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='new_pcr_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='total_antigen_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='total_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='total_pcr_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidedeathsdate',
            name='new_deaths_rolling',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidedeathsdate',
            name='total_deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidehospitalizationsdate',
            name='total_hospitalizations',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidehospitalizationsdate',
            name='total_icu_admissions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='new_antigen_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='new_external_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='new_pcr_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='new_state_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='new_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='new_tests_rolling',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='total_antigen_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='total_pcr_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='total_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='confirmed_cases_newly_reported',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_antigen_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_completed_mdh',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_completed_private',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_completed_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_confirmed_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_confirmed_statewide_deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_hospitalized',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_pcr_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_positive_tests',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_probable_cases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_probable_statewide_deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_statewide_deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='cumulative_statewide_recoveries',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='probable_cases_newly_reported',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
