# Generated by Django 3.1.3 on 2020-11-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0039_auto_20201014_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='bool_ltc',
            field=models.BooleanField(null=True),
        ),
    ]
