# Generated by Django 3.1.3 on 2020-12-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0040_auto_20201124_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewidetotaldate',
            name='cumulative_icu',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
