# Generated by Django 3.1.3 on 2020-12-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0041_statewidetotaldate_cumulative_icu'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewidetotaldate',
            name='icu_total_daily_change',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
