# Generated by Django 3.1.3 on 2021-01-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_vacadmintotaldate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacDistTotalDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField()),
                ('allocated_total', models.IntegerField(null=True)),
                ('allocated_pfizer', models.IntegerField(null=True)),
                ('allocated_moderna', models.IntegerField(null=True)),
                ('distributed_pfizer', models.IntegerField(null=True)),
                ('distributed_moderna', models.IntegerField(null=True)),
                ('providers_received_vac', models.IntegerField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
