# Generated by Django 3.1.3 on 2021-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0044_vacdisttotaldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacadmintotaldate',
            name='admin_people_total',
            field=models.IntegerField(null=True),
        ),
    ]
