# Generated by Django 3.1.3 on 2021-01-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0045_vacadmintotaldate_admin_people_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacCountyDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=50)),
                ('data_date', models.DateField(db_index=True)),
                ('people_admin_total', models.IntegerField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
