# Generated by Django 3.1.3 on 2021-01-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0047_auto_20210114_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacadmintotaldate',
            old_name='distributed_moderna_cdc_ltc',
            new_name='shipped_moderna_cdc_ltc',
        ),
        migrations.RenameField(
            model_name='vacadmintotaldate',
            old_name='distributed_moderna_mn_providers',
            new_name='shipped_moderna_mn_providers',
        ),
        migrations.RenameField(
            model_name='vacadmintotaldate',
            old_name='distributed_moderna_total',
            new_name='shipped_moderna_total',
        ),
        migrations.RenameField(
            model_name='vacadmintotaldate',
            old_name='distributed_pfizer_cdc_ltc',
            new_name='shipped_pfizer_cdc_ltc',
        ),
        migrations.RenameField(
            model_name='vacadmintotaldate',
            old_name='distributed_pfizer_mn_providers',
            new_name='shipped_pfizer_mn_providers',
        ),
        migrations.RenameField(
            model_name='vacadmintotaldate',
            old_name='distributed_pfizer_total',
            new_name='shipped_pfizer_total',
        ),
    ]
