# Generated by Django 3.1.3 on 2021-01-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0048_auto_20210114_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacGenderDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(db_index=True, max_length=25)),
                ('data_date', models.DateField(db_index=True)),
                ('people_admin_total', models.IntegerField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
