# Generated by Django 3.1.3 on 2021-01-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0049_vacgenderdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacgenderdate',
            old_name='people_admin_total',
            new_name='people_admin',
        ),
    ]
