# Generated by Django 3.1.3 on 2021-01-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0050_auto_20210115_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacadmintotaldate',
            old_name='data_date',
            new_name='released_date',
        ),
        migrations.RenameField(
            model_name='vaccountydate',
            old_name='data_date',
            new_name='released_date',
        ),
        migrations.RenameField(
            model_name='vacdisttotaldate',
            old_name='data_date',
            new_name='released_date',
        ),
        migrations.RenameField(
            model_name='vacgenderdate',
            old_name='data_date',
            new_name='released_date',
        ),
    ]
