# Generated by Django 3.1.3 on 2021-01-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0051_auto_20210126_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacadmintotaldate',
            name='asof_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vaccountydate',
            name='asof_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vacdisttotaldate',
            name='asof_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vacgenderdate',
            name='asof_date',
            field=models.DateField(null=True),
        ),
    ]
