# Generated by Django 3.1.3 on 2021-02-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0052_auto_20210126_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countytestdate',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='death',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statewideagedate',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='sample_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statewidecasesbysampledate',
            name='update_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statewidedeathsdate',
            name='reported_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statewidedeathsdate',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statewidedeathsdate',
            name='update_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statewidehospitalizationsdate',
            name='reported_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statewidehospitalizationsdate',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statewidehospitalizationsdate',
            name='update_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='reported_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statewidetestsdate',
            name='update_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statewidetotaldate',
            name='update_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacadmintotaldate',
            name='asof_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacadmintotaldate',
            name='released_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vaccountydate',
            name='asof_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacdisttotaldate',
            name='asof_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacdisttotaldate',
            name='released_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vacgenderdate',
            name='asof_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcasesdate',
            name='data_date',
            field=models.DateField(db_index=True),
        ),
    ]
