# Generated by Django 3.1.3 on 2021-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0053_auto_20210203_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacadmintotaldate',
            name='admin_people_completed_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaccountydate',
            name='people_admin_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vacgenderdate',
            name='people_admin_completed',
            field=models.IntegerField(null=True),
        ),
    ]
