# Generated by Django 3.1.3 on 2021-02-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0055_statewideracedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewideracedate',
            name='bool_ethnicity_paired',
            field=models.BooleanField(default=True),
        ),
    ]
