# Generated by Django 3.1.3 on 2021-03-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0056_statewideracedate_bool_ethnicity_paired'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacadmintotaldate',
            name='admin_jj',
            field=models.IntegerField(null=True),
        ),
    ]
