# Generated by Django 3.1.3 on 2021-03-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0057_vacadmintotaldate_admin_jj'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacadmintotaldate',
            name='shipped_jj_cdc_ltc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vacadmintotaldate',
            name='shipped_jj_mn_providers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vacadmintotaldate',
            name='shipped_jj_total',
            field=models.IntegerField(null=True),
        ),
    ]
