# Generated by Django 3.1.3 on 2021-04-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0059_vacagepercentagedate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacAgePercentageDate',
            new_name='VacCountyAgePercentageDate',
        ),
    ]
