# Generated by Django 3.1.3 on 2021-04-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0060_auto_20210413_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccountyagepercentagedate',
            name='age_group',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
