from django.core.management.base import BaseCommand
from stats.utils import slack_latest

from django.conf import settings

class Command(BaseCommand):

    TEST_TEXT='''1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Praesent semper feugiat nibh sed. Scelerisque purus semper eget duis at. Amet venenatis urna cursus eget nunc scelerisque. At imperdiet dui accumsan sit amet nulla facilisi. Ut placerat orci nulla pellentesque dignissim enim. Nunc id cursus metus aliquam. Pharetra sit amet aliquam id diam maecenas ultricies. Sit amet purus gravida quis blandit turpis cursus in hac. Donec et odio pellentesque diam volutpat commodo. Egestas maecenas pharetra convallis posuere morbi leo. Sed arcu non odio euismod lacinia at quis. Lobortis mattis aliquam faucibus purus in massa tempor nec. Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Tortor condimentum lacinia quis vel. Platea dictumst vestibulum rhoncus est. Amet justo donec enim diam vulputate.

    2Purus viverra accumsan in nisl nisi. Hac habitasse platea dictumst quisque sagittis purus. Quam adipiscing vitae proin sagittis nisl rhoncus. Turpis egestas maecenas pharetra convallis posuere morbi leo. Sed turpis tincidunt id aliquet risus. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Malesuada fames ac turpis egestas integer eget. Senectus et netus et malesuada fames ac turpis egestas integer. Vitae ultricies leo integer malesuada nunc vel. Nunc sed augue lacus viverra. Placerat in egestas erat imperdiet sed euismod nisi porta. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam.

    3Commodo odio aenean sed adipiscing diam donec adipiscing tristique. In ornare quam viverra orci sagittis eu. Morbi leo urna molestie at elementum eu. Nullam eget felis eget nunc lobortis mattis aliquam. Egestas egestas fringilla phasellus faucibus. Vitae semper quis lectus nulla at. Accumsan tortor posuere ac ut consequat semper viverra. Volutpat lacus laoreet non curabitur gravida. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Morbi leo urna molestie at elementum. Sit amet massa vitae tortor condimentum lacinia. Lacus vel facilisis volutpat est. Hendrerit gravida rutrum quisque non tellus orci. Diam vel quam elementum pulvinar etiam. At lectus urna duis convallis convallis tellus id interdum. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Nisl purus in mollis nunc sed id semper risus in.

    4Ut ornare lectus sit amet est placerat. Ornare arcu dui vivamus arcu felis bibendum. Tortor at auctor urna nunc id cursus metus aliquam. Nascetur ridiculus mus mauris vitae. Metus dictum at tempor commodo ullamcorper a. Fermentum iaculis eu non diam phasellus vestibulum lorem. Sem nulla pharetra diam sit. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Risus sed vulputate odio ut enim blandit volutpat maecenas. Gravida in fermentum et sollicitudin. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Volutpat blandit aliquam etiam erat velit. Venenatis a condimentum vitae sapien pellentesque. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. A arcu cursus vitae congue mauris rhoncus.

    5Dignissim sodales ut eu sem integer. Ut porttitor leo a diam. Non tellus orci ac auctor augue mauris augue neque. Nunc pulvinar sapien et ligula ullamcorper malesuada. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Neque aliquam vestibulum morbi blandit cursus risus at. Amet mattis vulputate enim nulla aliquet porttitor. Pellentesque nec nam aliquam sem et tortor consequat id. Velit laoreet id donec ultrices. In dictum non consectetur a erat nam at. Purus gravida quis blandit turpis cursus in hac habitasse. Iaculis urna id volutpat lacus laoreet non curabitur. Tortor at risus viverra adipiscing at in tellus. Nibh tortor id aliquet lectus proin nibh nisl. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum.

    6Dui ut ornare lectus sit amet est placerat in. Dignissim convallis aenean et tortor at risus viverra adipiscing. Enim blandit volutpat maecenas volutpat blandit. Eu feugiat pretium nibh ipsum consequat. Id diam maecenas ultricies mi. Quis varius quam quisque id diam vel quam. Tempus urna et pharetra pharetra massa massa ultricies. Vitae tortor condimentum lacinia quis vel. Nunc scelerisque viverra mauris in. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Auctor neque vitae tempus quam pellentesque. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget.

    7Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Id porta nibh venenatis cras sed felis eget. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Congue eu consequat ac felis donec et odio pellentesque. Scelerisque in dictum non consectetur a erat nam at. Nibh ipsum consequat nisl vel pretium lectus quam id. Cursus euismod quis viverra nibh cras. Felis imperdiet proin fermentum leo vel. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Auctor elit sed vulputate mi sit amet mauris. Tellus rutrum tellus pellentesque eu tincidunt tortor. Sollicitudin tempor id eu nisl. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Sapien et ligula ullamcorper malesuada. In tellus integer feugiat scelerisque varius morbi. Habitant morbi tristique senectus et netus et. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque.

    8Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Amet dictum sit amet justo donec enim diam vulputate ut. Enim lobortis scelerisque fermentum dui faucibus. Risus sed vulputate odio ut enim blandit volutpat maecenas. Lorem dolor sed viverra ipsum nunc. Elit sed vulputate mi sit amet mauris commodo quis. Lectus nulla at volutpat diam ut venenatis tellus in. Sit amet volutpat consequat mauris nunc congue nisi. Ultrices vitae auctor eu augue ut lectus arcu. Ultrices sagittis orci a scelerisque purus semper. Ultricies leo integer malesuada nunc vel risus commodo. Nisi quis eleifend quam adipiscing vitae proin sagittis. Quam id leo in vitae turpis massa sed. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. At augue eget arcu dictum varius duis at consectetur.

    9Tristique risus nec feugiat in fermentum posuere urna nec tincidunt. Blandit volutpat maecenas volutpat blandit aliquam etiam. Pulvinar neque laoreet suspendisse interdum. In eu mi bibendum neque egestas congue quisque. Dolor morbi non arcu risus quis varius quam quisque id. Nisi porta lorem mollis aliquam ut porttitor leo. Ultricies lacus sed turpis tincidunt id. Semper auctor neque vitae tempus. Nisi lacus sed viverra tellus in hac habitasse platea. Ac turpis egestas integer eget aliquet. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Sed tempus urna et pharetra pharetra massa massa. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. At quis risus sed vulputate odio ut.

    10Libero enim sed faucibus turpis in eu mi bibendum. Lectus sit amet est placerat in egestas erat. Lacus luctus accumsan tortor posuere ac ut consequat semper. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Faucibus et molestie ac feugiat sed. Ac ut consequat semper viverra nam. Eget mi proin sed libero enim. Proin sed libero enim sed faucibus. Interdum varius sit amet mattis vulputate enim. Urna id volutpat lacus laoreet non curabitur gravida. Eros donec ac odio tempor orci dapibus ultrices in. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Id faucibus nisl tincidunt eget nullam non. Imperdiet massa tincidunt nunc pulvinar sapien et.'''

    def handle(self, *args, **options):
        slack_latest(self.TEST_TEXT, '#robot-dojo')
